coverage:
  ignore:
    - Sources/WeaverCommand
    - "Sources/WeaverCodeGen/*.generated.swift"
    - Sources/WeaverDI/Instance.swift
    - Tests
  status:
    patch: false
    changes: false
    project:
      default:
        target: 70
comment: false
